default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Martial@5009

development:
  <<: *default
  database: hatian_presidents_api_development
  username: postgres
  password: Martial@5009

test:
  <<: *default
  database: hatian_presidents_api_test
  username: postgres
  password: Martial@5009

production:
  <<: *default
  database: hatian_presidents_api_production
  username: hatian_presidents_api
  password: <%= ENV["HATIAN_PRESIDENTS_API_DATABASE_PASSWORD"] %>
  adapter: postgresql
